# Generated by Django 4.2.10 on 2024-02-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usename',
            new_name='username',
        ),
    ]
